// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUa2v85b9OZglYODEaYgOxphm5FNdZGA4',
    appId: '1:891734579345:android:33569557c5df4ad6a3c730',
    messagingSenderId: '891734579345',
    projectId: 'string-e67f9',
    storageBucket: 'string-e67f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwt-L7EyVsseVBO2V-5BMZCAR8NEDZYjA',
    appId: '1:891734579345:ios:844fab0708c66453a3c730',
    messagingSenderId: '891734579345',
    projectId: 'string-e67f9',
    storageBucket: 'string-e67f9.appspot.com',
    androidClientId: '891734579345-cuntv9l1h2b7kul6o8bkpjo57vp3jn13.apps.googleusercontent.com',
    iosClientId: '891734579345-k4g7m6df3hgjb6dau7ahngspi00tpmln.apps.googleusercontent.com',
    iosBundleId: 'com.string',
  );
}
