// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
//  import 'firebase_options.dart';
//  // ...

// // ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBOgIroIKlKJMSBdwrO9yLcEgRZrNnJ3eE',
//     appId: '1:891734579345:web:0d228a48be707d22a3c730',
//     messagingSenderId: '891734579345',
//     projectId: 'string-e67f9',
//     authDomain: 'string-e67f9.firebaseapp.com',
//     storageBucket: 'string-e67f9.appspot.com',
//     measurementId: 'G-WGPCVSYP6W',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCUa2v85b9OZglYODEaYgOxphm5FNdZGA4',
//     appId: '1:891734579345:android:0120cc538b0a798fa3c730',
//     messagingSenderId: '891734579345',
//     projectId: 'string-e67f9',
//     storageBucket: 'string-e67f9.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCwt-L7EyVsseVBO2V-5BMZCAR8NEDZYjA',
//     appId: '1:891734579345:ios:78983096dfb21435a3c730',
//     messagingSenderId: '891734579345',
//     projectId: 'string-e67f9',
//     storageBucket: 'string-e67f9.appspot.com',
//     iosClientId: '891734579345-ltjdiiaagp93nfks0vj016t0mk1alv9b.apps.googleusercontent.com',
//     iosBundleId: 'com.example.stringApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCwt-L7EyVsseVBO2V-5BMZCAR8NEDZYjA',
//     appId: '1:891734579345:ios:78983096dfb21435a3c730',
//     messagingSenderId: '891734579345',
//     projectId: 'string-e67f9',
//     storageBucket: 'string-e67f9.appspot.com',
//     iosClientId: '891734579345-ltjdiiaagp93nfks0vj016t0mk1alv9b.apps.googleusercontent.com',
//     iosBundleId: 'com.example.stringApp',
//   );
// }
